server:
  port: 8081

spring:
  application:
    name: JpaMapping

  datasource:
    username: root
    password: Avyaan@123
    url: jdbc:mysql://localhost:3306/jpamapping

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true


  main:
    allow-bean-definition-overriding: true